### ISSUE TITLE
esp 32 cozmars

### ISSUE THREAD

**Issue by Anugaradhawa** [hyansuper/rcute-cozmars#26]
can i build this cozmars using esp32 board? please reply

**Comment by hyansuper** [comment]
It may be possible, see the esp32-s3-box, it has many functions( screen, sound, etc), but you need total redesign

**Comment by Anugaradhawa** [comment]
> It may be possible, see the esp32-s3-box, it has many functions( screen, sound, etc), but you need total redesign

thanks for your reply but I was asked about the ESP32-S board by connecting display and amplifier to the board

**Comment by hyansuper** [comment]
I believe all ESP32 board can control display and amplifier,  just not sure If it's fast enough(eg. display update rate...)

**Comment by Anugaradhawa** [comment]
Hey please tell me how you display facial expressions on that TFT display please tell me

**Comment by hyansuper** [comment]
Basically I just draw two squares at random (x,y) coordinate on computer side, and send the picture to robot.
You can draw any animation, all the robot get is a picture. To optimize, you can only send updated area and location infomation to  the robot.

**Comment by Anugaradhawa** [comment]
> Basically I just draw two squares at random (x,y) coordinate on computer side, and send the picture to robot. You can draw any animation, all the robot get is a picture. To optimize, you can only send updated area and location infomation to the robot.

How you animate it

**Comment by Anugaradhawa** [comment]
> Basically I just draw two squares at random (x,y) coordinate on computer side, and send the picture to robot. You can draw any animation, all the robot get is a picture. To optimize, you can only send updated area and location infomation to the robot.

Are you mean "cube animation.py" code?

**Comment by hyansuper** [comment]
no, it's eye_animation.py. but it's badly written and no comment

**Comment by Anugaradhawa** [comment]
Can i upload only "eye  animation.py" code directly to the TFT display?

**Comment by hyansuper** [comment]
No, It's in python and runs on client(computer) side, can't upload to Arduino/esp32 boards.

**Comment by Anugaradhawa** [comment]
how do I upload the code, and use which software??

**Comment by Anugaradhawa** [comment]
how you upload code to the board?

**Comment by Anugaradhawa** [comment]
???

**Comment by hyansuper** [comment]
No uploading. This repo runs on client side, meaning you computer
